name: Test codebase (only run unit test)
run-name: ${{ github.actor }} is running go unit tests
on:
  push:
    branches:
      - main
      - test

jobs:
  run_tests:
    name: Run unit tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.x
      - name: Cache Go
        uses: actions/cache@v1
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test ./test
